# Generated by Django 3.2.3 on 2021-06-23 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Categoría')),
                ('categoria', models.CharField(max_length=20, verbose_name='Nombre Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('nombreUser', models.CharField(max_length=50, verbose_name='Nombre del Usuario')),
                ('correo', models.EmailField(max_length=40, primary_key=True, serialize=False, verbose_name='Correo')),
                ('contrasenia', models.CharField(max_length=20, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('idNoticia', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Noticia')),
                ('tituloNoticia', models.CharField(max_length=60, verbose_name='Título de la Noticia')),
                ('autor', models.CharField(max_length=50, verbose_name='Autor Noticia')),
                ('descNoticia', models.TextField(max_length=1000, verbose_name='Texto de Noticia')),
                ('lugarNoticia', models.CharField(max_length=40, verbose_name='Lugar de los hechos')),
                ('fechaNoticia', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
