# Generated by Django 3.2.3 on 2021-06-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_noticia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Evidencia', verbose_name='Imagen de Referencia'),
        ),
    ]
